version : "3"
services : 
  db : 
    image : postgres
    container_name : postgres
    restart : always
    ports : 
      - "5432:5432"
    environment : 
      POSTGRES_USER : root 
      POSTGRES_PASSWORD : "9240"
    volumes :
      - /var/lib/postgresql/data 

